### ISSUE TITLE
labelme data errors

### ISSUE THREAD

**Issue by jsseng** [htrick/Senior-Project#17]
Could you take a look these 2 in the labelme dataset:  09-53-54-10-20-2018-873 and 09-55-35-10-20-2018-804.  I am not sure why it is producing the incorrect image in the validation mask.

**Comment by jsseng** [comment]
I went through all the files and these are the bad masks.  Maybe they are all related to the same bug:

08-34-12-03-28-2018-804_validation_mask.jpg
08-35-05-03-28-2018-953_validation_mask.jpg
09-08-37-03-30-2018-587_validation_mask.jpg
09-53-54-10-20-2018-873_validation_mask.jpg
09-55-05-10-20-2018-742_validation_mask.jpg
09-55-35-10-20-2018-804_validation_mask.jpg
10_16_18-10_validation_mask.jpg
10_16_18-11_validation_mask.jpg
11_12_18_54_validation_mask.jpg
11_3_18_1_2_validation_mask.jpg
12_10_18_25_validation_mask.jpg
12_11_18_14_validation_mask.jpg
12_22_18_1_51_validation_mask.jpg
12_24_18_52_validation_mask.jpg
15-45-59-03-31-2018-804_validation_mask.jpg
15-46-28-03-31-2018-500_validation_mask.jpg
15-46-40-03-31-2018-844_validation_mask.jpg
15-46-53-03-31-2018-201_validation_mask.jpg
15-46-54-03-31-2018-320_validation_mask.jpg
15-47-42-03-31-2018-981_validation_mask.jpg
15-47-45-03-31-2018-111_validation_mask.jpg
15-47-46-03-31-2018-226_validation_mask.jpg
15-47-50-03-31-2018-593_validation_mask.jpg
15-47-51-03-31-2018-596_validation_mask.jpg
15-49-21-03-31-2018-295_validation_mask.jpg

**Comment by htrick** [comment]
It looks like most of those are because there were multiple polygons or there was a polygon that was deleted and then redrawn. I'll adjust the script to fix that.

For 5 of them (08-34-12-03-28-2018-804, 10_16_18-10, 10_16_18-11, 12_24_18_52, and 15-45-59-03-31-2018-804) one corner of the polygon does not extend all the way to the bottom of the image. For example, on image 08-34-12-03-28-2018-804, the bottom-right corner of the polygon is (479, 268), but the bottom-left is (1, 269), causing a one pixel slant on the bottom edge. This makes the dataExtractor script draw half of the mask validation dots on the bottom of the image. I'm not sure how to fix these 5 images.

**Comment by htrick** [comment]
Maybe just those 5 XML files should be adjusted to change the coordinates of the corner

**Comment by jsseng** [comment]
Okay, let me look at those 5 files in the original dataset.  Maybe I can adjust the polygon and regenerate the XML files.

**Comment by jsseng** [comment]
For those 5 XML files, there were drawing errors in the polygons.  I fixed the polygons and regenerated the XML files.  I viewed the validation masks and they are correct now.  I have uploaded the corrected dataset to the URL.

**Comment by htrick** [comment]
I fixed the script, but I just noticed that 15-46-40-03-31-2018-844 also has the same problem with the slanted bottom edge. Sorry I didn't list it with the other 5.

**Comment by jsseng** [comment]
I went through and fixed that last one.  All the other ones look okay and I uploaded the new dataset.
